env:
  global:
  - secure: bPVOR7HJKT6tNEkRAkgXIi50c/jb+XfjRA/NuBrChw6ngLYkfyGAE+XMKAPgeEhicshgAAlruGlusuy03kY369Abm0b2co+zOk2FZxUPdu90sJbTEC+88DF9s9595uvk++8LURhut7g3S2UQ0jc6Uqg4U3qK4V3qJzU1SZ5mIZc=

language: php
sudo: false
matrix:
  include:
  - php: '7.2'
  - php: '7.3'
    env:
    - EXECUTE_AFTER_SCRIPT=true

cache:
  directories:
  - "$HOME/.composer/cache"
  
before_install:
- travis_retry composer self-update
- travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script:
- composer test:ci

after_script:
- if [[ $EXECUTE_AFTER_SCRIPT == 'true' ]]; then bash <(curl -s https://gist.githubusercontent.com/neilime/769d733c52acdecea8d2548fb3aca3ff/raw/travis_ci_php_publish_build.sh);fi
